<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7jol7tc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7jol7tc/appProdProjectContainer.php') {
    touch(__DIR__.'/Container7jol7tc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container7jol7tc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container7jol7tc\appProdProjectContainer(array(
    'container.build_hash' => '7jol7tc',
    'container.build_id' => 'b516d1ce',
    'container.build_time' => 1534209462,
), __DIR__.\DIRECTORY_SEPARATOR.'Container7jol7tc');
